[tool.poetry]
name = "eat-db"
version = "0.1.0"
description = ""
authors = ["Gabriel <gabriel59kg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
blue-chip = "*"

[tool.poetry.dev-dependencies]
black = "19.10b0"
pytest = "^5.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
